name: automation

on:
  workflow_dispatch:
   inputs:
     environment:
        description: choose the environment
        type: choice
        options:
          - dev
          - main
          - test
jobs:
  code_received:
      runs-on: ubuntu-latest
      steps:
        - name: print code is received
          run: echo "the code is received"
  build:
      needs: code_received
      runs-on: ubuntu-latest
      steps:
        - name: build the code
          run: echo "build the code"
  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: test the application
          run: echo "testing the app"
  deploy:
      if: inputs.environment== 'dev'
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: deploy the application
          run: echo "please deploy the application"
    
